### ISSUE TITLE
AppInfo list view is hogging screen

### ISSUE THREAD

**Issue by tir38** [STAR-ZERO/Hyperion-AppInfo#1]
If I add this plugin to list of core plugins then this list view pushes all other items off the drawer and I see nothing. I don't see what in your layout source could be causing this. Is it possible the version you have here isn't the same version on Maven central?

**Comment by STAR-ZERO** [comment]
It was not reproduced.

This plugin is not available on Maven Central. This plugin is only available on jCenter. The version of plugin in here is same on jCenter.

Can you tell me following?
* Send me screenshot
* Your dependencies in build.gradle
* Version of android

**Comment by STAR-ZERO** [comment]
Let me close.
If you have anything, please reopen it.

**Comment by tir38** [comment]
Weird. If I add this plugin to the Hyperion-Sample project it works fine, but if I add it to my own project it produced the problem and hogs the whole drawer. I'll try to hunt down the root cause (or add other plugins to see if the problem is not specific to this plugin)
