### ISSUE TITLE
Are you planing to transfer from jcenter to any other hosting service ?

### ISSUE THREAD

**Issue by matsujun** [STAR-ZERO/Hyperion-AppInfo#4]
JCenter shuts down on March 31st, 2021(submission) / Feb 1st, 2022(download)
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by STAR-ZERO** [comment]
Sorry, please wait for a moment. 🙇 
I'm planning to migrate to another repository.

**Comment by STAR-ZERO** [comment]
Available from Maven Central now.

I couldn't use the previous groupId `com.star_zero`. So I have changed the groupId to `com.star-zero`. (Changed from underscore to hyphen)

Please change the groupId. 🙏
